name: test-token-content-slot
base: core18 
version: '0.1' 
summary: baba yaga
description: |
  baba yaga

grade: stable
confinement: strict

slots:
  edgex-secret-token:
    interface: content
    content: edgex-secretstore-token
    source:
      read: [$SNAP/my-profile, $SNAP/your-profile]

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: dump
    source: .

